line-length = 120
select = ["E", "F"]            # W-series included automatically with E
ignore = [
  "E501","F401","E402","E203","E303","E302","E305",
  "W291","W292","W293","W391",
  "F541","F811"
]
